In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

In [2]:
data = np.load(r'D:\heat_wave\SSTa_93_19_expand_all_area.npz')
data.files

['time', 'lat', 'lon', 'ssta']

In [3]:
lat = data['lat'][339:381]   # -5.125 -4.875 ... 4.875  5.125

In [4]:
lon = data['lon'][760:961]  # 190.125 190.375 ... 239.875  240.125

In [5]:
lat.shape

(42,)

In [6]:
ssta = data['ssta'][:]
ssta.shape

(9861, 720, 1440)

In [7]:
ssta = ssta[:,339:381,760:961]

In [8]:
# JJA   93
date_93_1 = 151
date_93_2 = 243
data_1 = date_93_1
data_2 = date_93_2

ssta_93 = ssta[data_1:data_2,:,:]

In [9]:
# JJA   94
date_94_1 = 516
date_94_2 = 608
data_1 = date_94_1
data_2 = date_94_2

ssta_94 = ssta[data_1:data_2,:,:]

In [10]:
# JJA   95
date_95_1 = 881
date_95_2 = 973
data_1 = date_95_1
data_2 = date_95_2

ssta_95 = ssta[data_1:data_2,:,:]

In [11]:
# JJA   96
date_96_1 = 1247
date_96_2 = 1339
data_1 = date_96_1
data_2 = date_96_2

ssta_96 = ssta[data_1:data_2,:,:]

In [12]:
# JJA   97
date_97_1 = 1612
date_97_2 = 1704
data_1 = date_97_1
data_2 = date_97_2

ssta_97 = ssta[data_1:data_2,:,:]

In [13]:
# JJA   98
date_98_1 = 1977
date_98_2 = 2069
data_1 = date_98_1
data_2 = date_98_2

ssta_98 = ssta[data_1:data_2,:,:]

In [14]:
# JJA   99
date_99_1 = 2324
date_99_2 = 2434
data_1 = date_99_1
data_2 = date_99_2

ssta_99 = ssta[data_1:data_2,:,:]

In [15]:
# JJA   00
date_00_1 = 2708
date_00_2 = 2799
data_1 = date_00_1
data_2 = date_00_2

ssta_00 = ssta[data_1:data_2,:,:]

In [16]:
# JJA   01
date_01_1 = 3073
date_01_2 = 3165
data_1 = date_01_1
data_2 = date_01_2

ssta_01 = ssta[data_1:data_2,:,:]

In [17]:
# JJA   02
date_02_1 = 3438
date_02_2 = 3529
data_1 = date_02_1
data_2 = date_02_2

ssta_02 = ssta[data_1:data_2,:,:]

In [18]:
# JJA   03
date_03_1 = 3803
date_03_2 = 3895
data_1 = date_03_1
data_2 = date_03_2

ssta_03 = ssta[data_1:data_2,:,:]

In [19]:
# JJA   04
date_04_1 = 4169
date_04_2 = 4261
data_1 = date_04_1
data_2 = date_04_2

ssta_04 = ssta[data_1:data_2,:,:]

In [20]:
# JJA   05
date_05_1 = 4534
date_05_2 = 4626
data_1 = date_05_1
data_2 = date_05_2

ssta_05 = ssta[data_1:data_2,:,:]

In [21]:
# JJA   06
date_06_1 = 4899
date_06_2 = 4990
data_1 = date_06_1
data_2 = date_06_2

ssta_06 = ssta[data_1:data_2,:,:]

In [22]:
# JJA   07
date_07_1 = 5264
date_07_2 = 5356
data_1 = date_07_1
data_2 = date_07_2

ssta_07 = ssta[data_1:data_2,:,:]

In [23]:
# JJA   08
date_08_1 = 5630
date_08_2 = 5722
data_1 = date_08_1
data_2 = date_08_2

ssta_08 = ssta[data_1:data_2,:,:]

In [24]:
# JJA   09
date_09_1 = 5995
date_09_2 = 6087
data_1 = date_09_1
data_2 = date_09_2

ssta_09 = ssta[data_1:data_2,:,:]

In [25]:
# JJA   10
date_10_1 = 6360
date_10_2 = 6452
data_1 = date_10_1
data_2 = date_10_2

ssta_10 = ssta[data_1:data_2,:,:]

In [26]:
# JJA   11
date_11_1 = 6725
date_11_2 = 6817
data_1 = date_11_1
data_2 = date_11_2

ssta_11 = ssta[data_1:data_2,:,:]

In [27]:
# JJA   12
date_12_1 = 7091
date_12_2 = 7183
data_1 = date_12_1
data_2 = date_12_2

ssta_12 = ssta[data_1:data_2,:,:]

In [28]:
# JJA   13
date_13_1 = 7456
date_13_2 = 7548
data_1 = date_13_1
data_2 = date_13_2

ssta_13 = ssta[data_1:data_2,:,:]

In [29]:
# JJA   14
date_14_1 = 7821
date_14_2 = 7913
data_1 = date_14_1
data_2 = date_14_2

ssta_14 = ssta[data_1:data_2,:,:]

In [30]:
# JJA   15
date_15_1 = 8186
date_15_2 = 8278
data_1 = date_15_1
data_2 = date_15_2

ssta_15 = ssta[data_1:data_2,:,:]

In [31]:
# JJA   16
date_16_1 = 8552
date_16_2 = 8644
data_1 = date_16_1
data_2 = date_16_2

ssta_16 = ssta[data_1:data_2,:,:]

In [32]:
# JJA   17
date_17_1 = 8917
date_17_2 = 9009
data_1 = date_17_1
data_2 = date_17_2

ssta_17 = ssta[data_1:data_2,:,:]

In [33]:
# JJA   18
date_18_1 = 9282
date_18_2 = 9374
data_1 = date_18_1
data_2 = date_18_2

ssta_18 = ssta[data_1:data_2,:,:]

In [34]:
# JJA   19
date_19_1 = 9647
date_19_2 = 9739
data_1 = date_19_1
data_2 = date_19_2

ssta_19 = ssta[data_1:data_2,:,:]

In [35]:
ssta_93_weio = np.mean(ssta_93[:], axis = (0,1,2)).reshape(-1,1)
ssta_94_weio = np.mean(ssta_94[:], axis = (0,1,2)).reshape(-1,1)
ssta_95_weio = np.mean(ssta_95[:], axis = (0,1,2)).reshape(-1,1)
ssta_96_weio = np.mean(ssta_96[:], axis = (0,1,2)).reshape(-1,1)
ssta_97_weio = np.mean(ssta_97[:], axis = (0,1,2)).reshape(-1,1)
ssta_98_weio = np.mean(ssta_98[:], axis = (0,1,2)).reshape(-1,1)
ssta_99_weio = np.mean(ssta_99[:], axis = (0,1,2)).reshape(-1,1)
ssta_00_weio = np.mean(ssta_00[:], axis = (0,1,2)).reshape(-1,1)
ssta_01_weio = np.mean(ssta_01[:], axis = (0,1,2)).reshape(-1,1)
ssta_02_weio = np.mean(ssta_02[:], axis = (0,1,2)).reshape(-1,1)
ssta_03_weio = np.mean(ssta_03[:], axis = (0,1,2)).reshape(-1,1)
ssta_04_weio = np.mean(ssta_04[:], axis = (0,1,2)).reshape(-1,1)
ssta_05_weio = np.mean(ssta_05[:], axis = (0,1,2)).reshape(-1,1)
ssta_06_weio = np.mean(ssta_06[:], axis = (0,1,2)).reshape(-1,1)
ssta_07_weio = np.mean(ssta_07[:], axis = (0,1,2)).reshape(-1,1)
ssta_08_weio = np.mean(ssta_08[:], axis = (0,1,2)).reshape(-1,1)
ssta_09_weio = np.mean(ssta_09[:], axis = (0,1,2)).reshape(-1,1)
ssta_10_weio = np.mean(ssta_10[:], axis = (0,1,2)).reshape(-1,1)
ssta_11_weio = np.mean(ssta_11[:], axis = (0,1,2)).reshape(-1,1)
ssta_12_weio = np.mean(ssta_12[:], axis = (0,1,2)).reshape(-1,1)
ssta_13_weio = np.mean(ssta_13[:], axis = (0,1,2)).reshape(-1,1)
ssta_14_weio = np.mean(ssta_14[:], axis = (0,1,2)).reshape(-1,1)
ssta_15_weio = np.mean(ssta_15[:], axis = (0,1,2)).reshape(-1,1)
ssta_16_weio = np.mean(ssta_16[:], axis = (0,1,2)).reshape(-1,1)
ssta_17_weio = np.mean(ssta_17[:], axis = (0,1,2)).reshape(-1,1)
ssta_18_weio = np.mean(ssta_18[:], axis = (0,1,2)).reshape(-1,1)
ssta_19_weio = np.mean(ssta_19[:], axis = (0,1,2)).reshape(-1,1)

In [36]:
ssta_93_19_weio = np.concatenate((ssta_93_weio, ssta_94_weio, ssta_95_weio,ssta_96_weio,
                                 ssta_97_weio, ssta_98_weio, ssta_99_weio, ssta_00_weio, ssta_01_weio,
                                 ssta_02_weio, ssta_03_weio, ssta_04_weio, ssta_05_weio, ssta_06_weio,
                                 ssta_07_weio, ssta_08_weio, ssta_09_weio,  ssta_10_weio, ssta_11_weio,
                                 ssta_12_weio, ssta_13_weio, ssta_14_weio, ssta_15_weio, ssta_16_weio,
                                 ssta_17_weio, ssta_18_weio, ssta_19_weio), axis = 0)

In [37]:
ssta_93_19_weio.shape

(27, 1)

In [38]:
np.savez(r'D:\heat_wave\pacific\SSTA_plot_JJA', ssta = ssta_93_19_weio)

array([ 0.93781849,  0.887229  , -1.20339954, -1.47402077, -0.17463467,
       -0.6452681 , -1.91588932, -2.00651787,  0.0228487 ,  0.02224701,
       -0.41835712, -0.61903205, -0.25964839,  0.3697548 ,  1.24915799,
        0.92848794,  1.52786183,  1.3372577 ,  1.28666822,  1.01604699,
        1.39538915,  0.87476793,  0.73415159,  0.06356698, -0.45705424,
        1.07231233,  1.00170332,  0.58105768, -0.18956354, -0.06016035,
       -1.56082308, -0.98140768, -0.95204111, -0.22266233, -1.06329088,
        0.01606348, -0.38456262, -0.35513502, -0.59578798, -1.09638967,
       -0.96704751,  0.19238497, -0.20824113, -1.09885747, -1.41952752,
       -1.37014142, -0.24073823,  0.33861613,  0.46801933,  0.57740299,
        1.07674026,  1.65615566,  1.81552711,  0.51487659,  0.59429199,
        0.80365123,  1.03303001,  1.26240879,  0.7618071 , -1.25881412,
       -2.44941826, -2.92005169, -0.09069732, -0.91130634, -1.03190315,
       -1.15256099, -0.47317001,  1.75620877,  1.13561196,  1.06

In [31]:
mslp_93_19 = np.concatenate((mslp_93, mslp_94, mslp_95, mslp_96, mslp_97,
                            mslp_98, mslp_99, mslp_00, mslp_01, mslp_02, mslp_03,
                            mslp_04, mslp_05, mslp_06, mslp_07, mslp_08, mslp_09,
                            mslp_10, mslp_11, mslp_12, mslp_13, mslp_14, mslp_15,
                            mslp_16, mslp_17, mslp_18, mslp_19),axis = 0)

In [32]:
mslp_93_19.shape

(2499, 73, 144)

In [33]:
mslp_93_19 = mslp_93_19 / 100

In [34]:
from sklearn.linear_model import LinearRegression
from statsmodels.tsa.seasonal import seasonal_decompose

nt, nlats, nlons = mslp_93_19.shape
print(mslp_93_19.shape) #(9855, 9, 7)
# 重塑为2D数组（time，lat*lon）
mslp2_2d = mslp_93_19.reshape(nt, nlats*nlons)

decomposition = seasonal_decompose(mslp2_2d, model='additive', period=12)

trend = decomposition.trend
for i in range(nlats*nlons):
    model = LinearRegression().fit(np.arange(nt).reshape(-1, 1), decomposition.observed[:, i])
    trend[:, i] = model.predict(np.arange(nt).reshape(-1, 1))
mslp_detrended = decomposition.observed - trend

# 重塑为3D数组（time，lat，lon）
mslp_detrended = mslp_detrended.reshape(nt, nlats, nlons)

mslp_detrended = mslp_detrended.reshape(-1,73,144)
print(mslp_detrended.shape)


print(np.mean(mslp_detrended))
print(np.max(mslp_detrended))
print(np.min(mslp_detrended))

(2499, 73, 144)
(2499, 73, 144)
4.023043172596827e-17
40.65622963273995
-59.535103494337136


In [35]:
mslp_detrended

array([[[  5.00754388,   5.00754388,   5.00754388, ...,   5.00754388,
           5.00754388,   5.00754388],
        [  0.95513501,   0.77557755,   0.60947605, ...,   1.46587068,
           1.26607506,   1.09293856],
        [ -2.44594114,  -3.12506086,  -3.83479242, ...,  -0.39173438,
          -1.03885466,  -1.76262012],
        ...,
        [ -8.76611503,  -9.30419882,  -9.72565273, ...,  -6.86333366,
          -7.53616821,  -8.1845742 ],
        [-13.68441839, -13.98179693, -14.20307039, ..., -12.90310033,
         -13.14057747, -13.44421371],
        [-12.67651619, -12.67651619, -12.67651619, ..., -12.67651619,
         -12.67651619, -12.67651619]],

       [[  3.17760102,   3.17760102,   3.17760102, ...,   3.17760102,
           3.17760102,   3.17760102],
        [ -3.09477264,  -3.15433416,  -3.2404201 , ...,  -2.76402813,
          -2.85383935,  -2.95696764],
        [ -8.01580558,  -8.42490537,  -8.78466078, ...,  -6.7115985 ,
          -7.18867447,  -7.61245274],
        ...,


In [36]:
mslp_detrended1 = np.mean(mslp_detrended, axis = 0)

In [37]:
mslp_detrended1

array([[ 2.15181570e-14,  2.15181570e-14,  2.15181570e-14, ...,
         2.15181570e-14,  2.15181570e-14,  2.15181570e-14],
       [ 5.92317978e-14, -5.14979993e-14, -9.91745923e-15, ...,
         4.28088493e-14, -1.26470352e-14, -5.27718014e-15],
       [ 4.08071602e-14, -1.00084451e-15,  3.92149076e-14, ...,
         2.79781533e-14, -7.75199566e-14, -3.37557557e-14],
       ...,
       [-2.95704060e-15, -8.91661472e-15, -7.72924919e-14, ...,
         6.80119337e-14,  4.45375807e-14,  5.43640541e-14],
       [ 2.17911146e-14,  8.83472745e-14, -8.43893893e-14, ...,
         4.06251885e-14,  7.51998170e-14, -5.14979993e-14],
       [-3.86689924e-15, -3.86689924e-15, -3.86689924e-15, ...,
        -3.86689924e-15, -3.86689924e-15, -3.86689924e-15]])

In [38]:
np.savez(r'D:\heat_wave\SLP_SLPA_JJA_all_area.npz',sea_level_press = mslp_93_19, 
         sea_level_press_anom = mslp_detrended)

In [39]:
mslp_93_19.shape

(2499, 73, 144)

In [40]:
mslp_weio_93_19 = mslp_93_19[:,32:41,21:28]

In [41]:
mslp_weio_93_19.shape

(2499, 9, 7)

In [42]:
mslp_weio_93_19_mean = np.mean(mslp_weio_93_19, axis = (1,2))

In [43]:
mslp_detrended_weio = mslp_detrended[:,32:41,21:28]

In [44]:
mslp_detrended_weio_93_19_mean = np.mean(mslp_detrended_weio, axis = (1,2))

In [45]:
mslp_pacific_93_19 = mslp_93_19[:,34:39,76:97]

In [46]:
mslp_detrended_pacific = mslp_detrended[:,34:39,76:97]

In [47]:
np.savez(r'D:\heat_wave\pacific\SLP_SLPA_JJA_pacific_area.npz',sea_level_press = mslp_pacific_93_19, 
         sea_level_press_anom = mslp_detrended_pacific)

In [48]:
np.savez(r'D:\heat_wave\WEIO\SLP_SLPA_JJA_WEIO_area.npz',sea_level_press = mslp_weio_93_19, 
         sea_level_press_anom = mslp_detrended_weio)

In [49]:
mslp_atlantic_93_19 = mslp_93_19[:,32:41,130:139]

In [50]:
mslp_detrended_atlantic = mslp_detrended[:,32:41,130:139]

In [51]:
np.savez(r'D:\heat_wave\atlantic\SLP_SLPA_JJA_atlantic_area.npz',sea_level_press = mslp_atlantic_93_19, 
         sea_level_press_anom = mslp_detrended_atlantic)